#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

print_colored() {
    color_code="$1"
    text="$2"
    printf "\033[${color_code}m%s\033[0m\n" "$text"
}

# 获取提交消息内容
MSG=$(cat "$1")

validate_commit_message() {
    # 确保提交消息格式为“一串英文: 具体内容”
    if ! echo "$MSG" | grep -qE "^[a-zA-Z]+: ."; then
        print_colored 31 "ERROR: Commit message format is incorrect!" # 31 是红色的 ANSI 代码
        print_colored 31 "Ensure your message starts with a sequence of English letters followed by ': '"
        exit 1
    else
        print_colored 32 "Commit message format is correct." # 32 是绿色的 ANSI 代码
    fi
}

validate_commit_message
